//#pragma src
//=========================================================
// src/EFM8BB31F32I-C-QFP32_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

// Button logic
// short press - fix/release values
// long press (5sec) - calibration. It will cycle from 0EC til 5EC. Release button when desired calibration is found. 
//  Then insert the probe into calibration liquid and wait until it will say, "OK".

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include "main.h"
#include "InitDevice.h"
#include "gen.h"
#include "button.h"
#include "pgm.h"
#include "pwm.h"
#include "temperature.h"

volatile glob_t glob;
volatile bit pwmOut0_update, allowStoreEEPROM = 0;
volatile pwmglob_t pwmglob;

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup(void) {
	// $[SiLabs Startup]
	// [SiLabs Startup]$
}

//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main(void) {
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();

  glob.LIGHT_on = 0;

  setval_PWMout(0); // LED is off

#ifdef DEBUGUART
	prnUART("START",1);
#endif

  loadSettingsEE();

  initADC();

	while(1){
	    processButtons(); // PWR/INC/DEC buttons
	    if(ADC_buffer_ready && glob.LIGHT_on==1){ // only check temperature if power is on
	        int16_t tmpr = ConvertADC2temp();
	        ADC_buffer_ready = 0;
	        if(tmpr>TEMPERATUREMAX){
	            if(glob.LED_step>0){glob.LED_step--;}else{glob.LIGHT_on=0;setval_PWMout(0);}
	            allowStoreEEPROM = 0;
	            glob.temp_cntr = 50*15; // delay for 15 seconds
	        }
	    }
	}

}
